"""added user active time

Revision ID: fee3cf108cb5
Revises: a2fd4ec0072b
Create Date: 2025-12-13 23:55:42.935638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee3cf108cb5'
down_revision: Union[str, Sequence[str], None] = 'a2fd4ec0072b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_time', sa.TIMESTAMP(timezone=True), nullable=True, comment='Время активности пользователя'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_time')
    # ### end Alembic commands ###
